### ISSUE TITLE
No tiene sentido la solución que me propones

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-II#1]
https://github.com/fjrf16/Exercises-JS-II/blob/b507527a7a8f19767c7fc0c5792f419908bd6789/assets/index.js#L10.

No tiene ningún sentido la solución que me propones ya que me compruebas la condición para nada, una de las opciones que sería la solución correcta es: 
```js
if (typeof value !== 'string' || typeof value !== 'number'){
   // elimina el valor del array ya que no cumple los requisitos
}
```

La solución que tu propones le hace perder al interprete tiempo comprobando condiciones en las que no se ejecutaría nada. Debes modificar esto

**Comment by fjrf16** [comment]
Tienes razón, he incluido la condición que indicabas pero la he modificado para que sea así:
`if (typeof array[index] !== 'string' && typeof array[index] !== 'number'){
            // elimina el valor del array ya que no cumple los requisitos
            array.splice(index,1);
            index--; // volvemos a disminuir el índice para que no se salte el siguiente
         }`

**Comment by gaal1le0** [comment]
Perfecto, recuerda que debes cerrar los issues.
