### ISSUE TITLE
Solución poco optimizada

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-II#2]
https://github.com/fjrf16/Exercises-JS-II/blob/b507527a7a8f19767c7fc0c5792f419908bd6789/assets/index.js#L29

Has creado dos bubble sort, uno para que ordene > y otro <, cuando en realidad podrías crear un único bubble sort parametrizado por el tipo de operación y ejecutar la comparación en función de ese parámetro que recibes, escribiendo así una sola vez el algoritmo bubble sort que sirve tanto para ordenar de mayor a menor como la viceversa. Debes arreglarlo.

PD: Felicidades!! tienes un código muy limpio y organizado, pero tienes esos fallos que quiero que revises.

**Comment by fjrf16** [comment]
He arreglado el issue con la solución esta:

`function bubbleSort(array, operation) {
    
    array = cleanArray(array); 

   
        for(let i=0; i<array.length; i++){

            for(let j=0; j<i; j++){ 
                
                if (operation == '<'){

                    if(array[i] < array[j]){ 

                        let correction = array[i]; 
                        array[i] = array[j];
                        array[j] = correction;
                    }
                }
                else if(operation == '>'){

                    if(array[i] >= array[j]){ 

                        let correction = array[i]; 
                        array[i] = array[j];
                        array[j] = correction;
                    }

                }
            }

        }
    

    return array;
  }
`

realizando el bubblesort en funcion del parametro '<' o '>'

**Comment by gaal1le0** [comment]
Perfecto reenvíamelo otra vez al mail para revisarlo completo!!
