### ISSUE TITLE
Estás modificando el parametro

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercises-JS-II#3]
https://github.com/fjrf16/Exercises-JS-II/blob/a3afe806e68bdbe200381450a0235bb9eaff350c/assets/index.js#L10

Has creado una función limpiadora donde modificas el array que recibes como parametro, eso no puede ser así nunca, debes crear un nuevo array que sea el limpio y cargar los resultados sobre eso, en este caso si haces eso podría producirte algunos fallos cuando intentes escalar el código, está prohibido modificar los parametros de una función.
Una solución correcta podría ser:

```js
// limpiar array de datos no validos
function cleanArray(array) {

    // usando programacion declarativa
    // return array.filter((data) => typeof(data) === 'string');

    // usando programacion imperativa
    let response = [];

    // recorrer el array completo
    for (let item of array) {
        if (typeof(item) === 'string') {
            response.push(item);
        }
    }

    return response;

}
```

Si te fijas en mi solución, yo nunca modifico el array que recibo como parametro simplemente creo uno nuevo y trabajo sobre el. Aplica siempre esto para evitar grandes dolores de cabeza.

Cambialo y adaptalo.

**Comment by fjrf16** [comment]
Manu, he resuelto los issues, te lo vuelvo a pasar por correo
